using Icarus_Item_Calculator.Models;
using Microsoft.EntityFrameworkCore;

public class ItemContext : DbContext
{
    public ItemContext(DbContextOptions<ItemContext> options) : base(options) { }

    public DbSet<Item> Items { get; set; }
    public DbSet<Recipe> Recipes { get; set; }
    public DbSet<RecipeItem> RecipeItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Item>()
            .Property(i => i.ItemId)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Recipe>()
            .HasOne(r => r.Item)
            .WithMany(i => i.Recipes)
            .HasForeignKey(r => r.ItemId)
            .OnDelete(DeleteBehavior.Cascade); // Delete Recipes when Item is deleted

        modelBuilder.Entity<RecipeItem>()
            .HasOne(ri => ri.Item)
            .WithMany()
            .HasForeignKey(ri => ri.ItemId)
            .OnDelete(DeleteBehavior.Restrict); // Prevent deletion of ingredients used in recipes

        modelBuilder.Entity<RecipeItem>()
            .HasOne(ri => ri.Recipe)
            .WithMany(r => r.Ingredients)
            .HasForeignKey(ri => ri.RecipeId)
            .OnDelete(DeleteBehavior.Cascade); // Delete RecipeItems when Recipe is deleted

        // Seed data if necessary
        modelBuilder.Entity<Item>().HasData(
            new Item { ItemId = 1, Name = "Aluminium Ingot", IsBaseItem = false },
            new Item { ItemId = 2, Name = "Aluminum Ore", IsBaseItem = true },
            new Item { ItemId = 3, Name = "Basic Fertilizer", IsBaseItem = false },
            new Item { ItemId = 4, Name = "Bone", IsBaseItem = true },
            new Item { ItemId = 5, Name = "Carbon Fiber", IsBaseItem = false },
            new Item { ItemId = 6, Name = "Carbon Paste", IsBaseItem = false },
            new Item { ItemId = 7, Name = "Charcoal", IsBaseItem = true },
            new Item { ItemId = 8, Name = "Coal Ore", IsBaseItem = true },
            new Item { ItemId = 9, Name = "Cocoa Seed", IsBaseItem = true },
            new Item { ItemId = 10, Name = "Coffee Bean", IsBaseItem = true },
            new Item { ItemId = 11, Name = "Composite Paste", IsBaseItem = false },
            new Item { ItemId = 12, Name = "Composites", IsBaseItem = false },
            new Item { ItemId = 13, Name = "Concrete Mix", IsBaseItem = false },
            new Item { ItemId = 14, Name = "Copper Ingot", IsBaseItem = false },
            new Item { ItemId = 15, Name = "Copper Nail", IsBaseItem = false },
            new Item { ItemId = 16, Name = "Copper Ore", IsBaseItem = true },
            new Item { ItemId = 17, Name = "Copper Wire", IsBaseItem = false },
            new Item { ItemId = 18, Name = "Corn", IsBaseItem = true },
            new Item { ItemId = 19, Name = "Crushed Bone", IsBaseItem = false },
            new Item { ItemId = 20, Name = "Dirt", IsBaseItem = true },
            new Item { ItemId = 21, Name = "Electronics", IsBaseItem = false },
            new Item { ItemId = 22, Name = "Epoxy", IsBaseItem = false },
            new Item { ItemId = 23, Name = "Exotics", IsBaseItem = true },
            new Item { ItemId = 24, Name = "Fiber", IsBaseItem = true },
            new Item { ItemId = 25, Name = "Fish Chunks", IsBaseItem = true },
            new Item { ItemId = 26, Name = "Flour", IsBaseItem = false },
            new Item { ItemId = 27, Name = "Fur", IsBaseItem = true },
            new Item { ItemId = 28, Name = "Glass", IsBaseItem = false },
            new Item { ItemId = 29, Name = "Gold Ore", IsBaseItem = true },
            new Item { ItemId = 30, Name = "Gold Wire", IsBaseItem = false },
            new Item { ItemId = 31, Name = "Gorse Flower", IsBaseItem = true },
            new Item { ItemId = 32, Name = "Growth Fertilizer", IsBaseItem = false },
            new Item { ItemId = 33, Name = "Gunpowder", IsBaseItem = false },
            new Item { ItemId = 34, Name = "High-Quality Fertilizer", IsBaseItem = false },
            new Item { ItemId = 35, Name = "Ice", IsBaseItem = true },
            new Item { ItemId = 36, Name = "Iron Ingot", IsBaseItem = false },
            new Item { ItemId = 37, Name = "Iron Nail", IsBaseItem = false },
            new Item { ItemId = 38, Name = "Iron Ore", IsBaseItem = true },
            new Item { ItemId = 39, Name = "Leather", IsBaseItem = true },
            new Item { ItemId = 40, Name = "Lily", IsBaseItem = true },
            new Item { ItemId = 41, Name = "Mammoth Tusk", IsBaseItem = true },
            new Item { ItemId = 42, Name = "Organic Resin", IsBaseItem = false },
            new Item { ItemId = 43, Name = "Oxite", IsBaseItem = true },
            new Item { ItemId = 44, Name = "Platinum Ingot", IsBaseItem = false },
            new Item { ItemId = 45, Name = "Platinum Ore", IsBaseItem = true },
            new Item { ItemId = 46, Name = "Poison Paste", IsBaseItem = false },
            new Item { ItemId = 47, Name = "Poison Sack", IsBaseItem = true },
            new Item { ItemId = 48, Name = "Polar Bear Pelt", IsBaseItem = true },
            new Item { ItemId = 49, Name = "Raw Meat", IsBaseItem = true },
            new Item { ItemId = 50, Name = "Raw Prime Meat", IsBaseItem = true },
            new Item { ItemId = 51, Name = "Reed Flower", IsBaseItem = true },
            new Item { ItemId = 52, Name = "Refined Gold", IsBaseItem = false },
            new Item { ItemId = 53, Name = "Refined Wood", IsBaseItem = false },
            new Item { ItemId = 54, Name = "Rope", IsBaseItem = false },
            new Item { ItemId = 55, Name = "Salt", IsBaseItem = true },
            new Item { ItemId = 56, Name = "Sandworm Scale", IsBaseItem = true },
            new Item { ItemId = 57, Name = "Scorpion Pincer", IsBaseItem = true },
            new Item { ItemId = 58, Name = "Scorpion Tail", IsBaseItem = true },
            new Item { ItemId = 59, Name = "Silica Ore", IsBaseItem = true },
            new Item { ItemId = 60, Name = "Spoiled Meat", IsBaseItem = true },
            new Item { ItemId = 61, Name = "Spoiled Plants", IsBaseItem = true },
            new Item { ItemId = 62, Name = "Sponge", IsBaseItem = true },
            new Item { ItemId = 63, Name = "Squash", IsBaseItem = true },
            new Item { ItemId = 64, Name = "Steel Bloom", IsBaseItem = false },
            new Item { ItemId = 65, Name = "Steel Ingot", IsBaseItem = false },
            new Item { ItemId = 66, Name = "Steel Rebar", IsBaseItem = false },
            new Item { ItemId = 67, Name = "Steel Screw", IsBaseItem = false },
            new Item { ItemId = 68, Name = "Stick", IsBaseItem = false },
            new Item { ItemId = 69, Name = "Stone", IsBaseItem = true },
            new Item { ItemId = 70, Name = "Sulfur", IsBaseItem = true },
            new Item { ItemId = 71, Name = "Tea", IsBaseItem = true },
            new Item { ItemId = 72, Name = "Titanium Ingot", IsBaseItem = false },
            new Item { ItemId = 73, Name = "Titanium Ore", IsBaseItem = true },
            new Item { ItemId = 74, Name = "Tree Sap", IsBaseItem = false },
            new Item { ItemId = 75, Name = "Wheat", IsBaseItem = true },
            new Item { ItemId = 76, Name = "Wild Berry", IsBaseItem = true },
            new Item { ItemId = 77, Name = "Wood", IsBaseItem = true },
            new Item { ItemId = 78, Name = "Worm Scale", IsBaseItem = true },
            new Item { ItemId = 79, Name = "Yeast", IsBaseItem = true },
            new Item { ItemId = 80, Name = "Crafting Bench", IsBaseItem = false },
            new Item { ItemId = 81, Name = "Anvil Bench", IsBaseItem = false },
            new Item { ItemId = 82, Name = "Wood Composter", IsBaseItem = false },
            new Item { ItemId = 83, Name = "Skinning Bench", IsBaseItem = false },
            new Item { ItemId = 84, Name = "Trophy Bench", IsBaseItem = false },
            new Item { ItemId = 85, Name = "Basic Fishing Bench", IsBaseItem = false },
            new Item { ItemId = 86, Name = "Mortar and Pestle", IsBaseItem = false },
            new Item { ItemId = 87, Name = "Herbalism Bench", IsBaseItem = false },
            new Item { ItemId = 88, Name = "Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 89, Name = "Carpentry Bench", IsBaseItem = false },
            new Item { ItemId = 90, Name = "Masonry Bench", IsBaseItem = false },
            new Item { ItemId = 91, Name = "Machining Bench", IsBaseItem = false },
            new Item { ItemId = 92, Name = "Cement Mixer", IsBaseItem = false },
            new Item { ItemId = 93, Name = "Glassworking Bench", IsBaseItem = false },
            new Item { ItemId = 94, Name = "Advanced Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 95, Name = "Alteration Bench", IsBaseItem = false },
            new Item { ItemId = 96, Name = "Fabricator", IsBaseItem = false },
            new Item { ItemId = 97, Name = "Material Processor", IsBaseItem = false },
            new Item { ItemId = 98, Name = "Chemistry Bench", IsBaseItem = false },
            new Item { ItemId = 99, Name = "Electric Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 100, Name = "Advanced Alteration Bench", IsBaseItem = false },
            new Item { ItemId = 101, Name = "Electric Carpentry Bench", IsBaseItem = false },
            new Item { ItemId = 102, Name = "Electric Masonry Bench", IsBaseItem = false },
            new Item { ItemId = 103, Name = "Stone Furnace", IsBaseItem = false },
            new Item { ItemId = 104, Name = "Concrete Furnace", IsBaseItem = false },
            new Item { ItemId = 105, Name = "Electric Furnace", IsBaseItem = false },
            new Item { ItemId = 106, Name = "MXC Furnace", IsBaseItem = false },
            new Item { ItemId = 107, Name = "Campfire", IsBaseItem = false },
            new Item { ItemId = 108, Name = "Drying Rack", IsBaseItem = false },
            new Item { ItemId = 109, Name = "Firepit", IsBaseItem = false },
            new Item { ItemId = 110, Name = "Fireplace", IsBaseItem = false },
            new Item { ItemId = 111, Name = "Cooking Station", IsBaseItem = false },
            new Item { ItemId = 112, Name = "Potbelly Stove", IsBaseItem = false },
            new Item { ItemId = 113, Name = "Kitchen Bench", IsBaseItem = false },
            new Item { ItemId = 114, Name = "Biofuel Stove", IsBaseItem = false },
            new Item { ItemId = 115, Name = "Marble Kitchen Bench", IsBaseItem = false },
            new Item { ItemId = 116, Name = "Electric Stove", IsBaseItem = false },
            new Item { ItemId = 117, Name = "MXC Campfire", IsBaseItem = false },
            new Item { ItemId = 118, Name = "Salting Station", IsBaseItem = false },
            new Item { ItemId = 119, Name = "Ice Box", IsBaseItem = false },
            new Item { ItemId = 120, Name = "Refrigerator", IsBaseItem = false },
            new Item { ItemId = 121, Name = "Deep Freeze", IsBaseItem = false },
            new Item { ItemId = 122, Name = "Wood Pile", IsBaseItem = false },
            new Item { ItemId = 123, Name = "Stone Pile", IsBaseItem = false },
            new Item { ItemId = 124, Name = "Oxidizer", IsBaseItem = false },
            new Item { ItemId = 125, Name = "Oxite Dissolver", IsBaseItem = false },
            new Item { ItemId = 126, Name = "Biofuel Oxite Dissolver", IsBaseItem = false },
            new Item { ItemId = 127, Name = "Dehumidifier", IsBaseItem = false },
            new Item { ItemId = 128, Name = "Electric Dehumidifier", IsBaseItem = false },
            new Item { ItemId = 129, Name = "Floor Torch", IsBaseItem = false },
            new Item { ItemId = 130, Name = "Brazier", IsBaseItem = false },
            new Item { ItemId = 131, Name = "Wall Torch", IsBaseItem = false },
            new Item { ItemId = 132, Name = "Basic Wall Light", IsBaseItem = false },
            new Item { ItemId = 133, Name = "Basic Ceiling Light", IsBaseItem = false },
            new Item { ItemId = 134, Name = "Directional Worklamp", IsBaseItem = false },
            new Item { ItemId = 135, Name = "Omnidirectional Worklamp", IsBaseItem = false },
            new Item { ItemId = 136, Name = "Heavy Heater", IsBaseItem = false },
            new Item { ItemId = 137, Name = "Heavy Air Conditioner", IsBaseItem = false },
            new Item { ItemId = 138, Name = "Rain Reservoir", IsBaseItem = false },
            new Item { ItemId = 139, Name = "Electric Water Pump", IsBaseItem = false },
            new Item { ItemId = 140, Name = "Biofuel Composter", IsBaseItem = false },
            new Item { ItemId = 141, Name = "Electric Composter", IsBaseItem = false },
            new Item { ItemId = 142, Name = "Biofuel Generator", IsBaseItem = false },
            new Item { ItemId = 143, Name = "Solar Panel", IsBaseItem = false },
            new Item { ItemId = 144, Name = "Water Wheel", IsBaseItem = false },
            new Item { ItemId = 145, Name = "Wind Turbine", IsBaseItem = false },
            new Item { ItemId = 146, Name = "Portable Biofuel Generator", IsBaseItem = false },
            new Item { ItemId = 147, Name = "Biofuel Radar", IsBaseItem = false },
            new Item { ItemId = 148, Name = "Biofuel Extractor", IsBaseItem = false },
            new Item { ItemId = 149, Name = "Electric Radar", IsBaseItem = false },
            new Item { ItemId = 150, Name = "Electric Extractor", IsBaseItem = false },
            new Item { ItemId = 151, Name = "Medium Wood Hedgehog", IsBaseItem = false },
            new Item { ItemId = 152, Name = "Wood Gate Fortification", IsBaseItem = false },
            new Item { ItemId = 153, Name = "Wood Wall Fortification", IsBaseItem = false },
            new Item { ItemId = 154, Name = "Wood Spikes Fortification", IsBaseItem = false },
            new Item { ItemId = 155, Name = "Lightning Rod", IsBaseItem = false },
            new Item { ItemId = 156, Name = "Water Sprinkler", IsBaseItem = false },
            new Item { ItemId = 157, Name = "Scorpion Pincer Trap", IsBaseItem = false },
            new Item { ItemId = 158, Name = "Scorpion Hedgehog", IsBaseItem = false },
            new Item { ItemId = 159, Name = "Wood Crop Plot", IsBaseItem = false },
            new Item { ItemId = 160, Name = "Iron Crop Plot", IsBaseItem = false },
            new Item { ItemId = 161, Name = "Hydroponic Crop Plot", IsBaseItem = false },
            new Item { ItemId = 162, Name = "Animal Bait", IsBaseItem = false },
            new Item { ItemId = 163, Name = "Poisoned Animal Bait", IsBaseItem = false },
            new Item { ItemId = 164, Name = "Titanium Plate", IsBaseItem = false },
            new Item { ItemId = 165, Name = "Flow Meter", IsBaseItem = false },
            new Item { ItemId = 166, Name = "Biofuel Deep-Mining Drill", IsBaseItem = false },
            new Item { ItemId = 167, Name = "Electric Deep-Mining Drill", IsBaseItem = false },
            new Item { ItemId = 168, Name = "Animal Fat", IsBaseItem = false },
            new Item { ItemId = 169, Name = "Electrolytic Oxygen Synthesizer", IsBaseItem = false }
        );

        // Seed Recipes (matching all recipes from migration)
        modelBuilder.Entity<Recipe>().HasData(
            new Recipe { RecipeId = 1, ItemId = 1 },
            new Recipe { RecipeId = 2, ItemId = 3 },
            new Recipe { RecipeId = 3, ItemId = 3 },
            new Recipe { RecipeId = 4, ItemId = 4 },
            new Recipe { RecipeId = 5, ItemId = 5 },
            new Recipe { RecipeId = 6, ItemId = 6 },
            new Recipe { RecipeId = 11, ItemId = 11 },
            new Recipe { RecipeId = 12, ItemId = 12 },
            new Recipe { RecipeId = 13, ItemId = 13 },
            new Recipe { RecipeId = 14, ItemId = 14 },
            new Recipe { RecipeId = 15, ItemId = 15 },
            new Recipe { RecipeId = 17, ItemId = 17 },
            new Recipe { RecipeId = 19, ItemId = 19 },
            new Recipe { RecipeId = 21, ItemId = 21 },
            new Recipe { RecipeId = 22, ItemId = 22 },
            new Recipe { RecipeId = 26, ItemId = 26 },
            new Recipe { RecipeId = 28, ItemId = 28 },
            new Recipe { RecipeId = 30, ItemId = 30 },
            new Recipe { RecipeId = 32, ItemId = 32 },
            new Recipe { RecipeId = 33, ItemId = 33 },
            new Recipe { RecipeId = 34, ItemId = 34 },
            new Recipe { RecipeId = 36, ItemId = 36 },
            new Recipe { RecipeId = 37, ItemId = 37 },
            new Recipe { RecipeId = 42, ItemId = 42 },
            new Recipe { RecipeId = 44, ItemId = 44 },
            new Recipe { RecipeId = 46, ItemId = 46 },
            new Recipe { RecipeId = 52, ItemId = 52 },
            new Recipe { RecipeId = 53, ItemId = 53 },
            new Recipe { RecipeId = 54, ItemId = 54 },
            new Recipe { RecipeId = 64, ItemId = 64 },
            new Recipe { RecipeId = 65, ItemId = 65 },
            new Recipe { RecipeId = 66, ItemId = 66 },
            new Recipe { RecipeId = 67, ItemId = 67 },
            new Recipe { RecipeId = 72, ItemId = 72 },
            new Recipe { RecipeId = 74, ItemId = 74 },
            new Recipe { RecipeId = 80, ItemId = 80 },
            new Recipe { RecipeId = 81, ItemId = 81 },
            new Recipe { RecipeId = 82, ItemId = 82 },
            new Recipe { RecipeId = 83, ItemId = 83 },
            new Recipe { RecipeId = 84, ItemId = 84 },
            new Recipe { RecipeId = 85, ItemId = 85 },
            new Recipe { RecipeId = 86, ItemId = 86 },
            new Recipe { RecipeId = 87, ItemId = 87 },
            new Recipe { RecipeId = 88, ItemId = 88 },
            new Recipe { RecipeId = 89, ItemId = 89 },
            new Recipe { RecipeId = 90, ItemId = 90 },
            new Recipe { RecipeId = 91, ItemId = 91 },
            new Recipe { RecipeId = 92, ItemId = 92 },
            new Recipe { RecipeId = 93, ItemId = 93 },
            new Recipe { RecipeId = 94, ItemId = 94 },
            new Recipe { RecipeId = 95, ItemId = 95 },
            new Recipe { RecipeId = 96, ItemId = 96 },
            new Recipe { RecipeId = 97, ItemId = 97 },
            new Recipe { RecipeId = 98, ItemId = 98 },
            new Recipe { RecipeId = 99, ItemId = 99 },
            new Recipe { RecipeId = 100, ItemId = 100 },
            new Recipe { RecipeId = 101, ItemId = 101 },
            new Recipe { RecipeId = 102, ItemId = 102 },
            new Recipe { RecipeId = 103, ItemId = 103 },
            new Recipe { RecipeId = 104, ItemId = 104 },
            new Recipe { RecipeId = 105, ItemId = 105 },
            new Recipe { RecipeId = 107, ItemId = 107 },
            new Recipe { RecipeId = 108, ItemId = 108 },
            new Recipe { RecipeId = 109, ItemId = 109 },
            new Recipe { RecipeId = 110, ItemId = 110 },
            new Recipe { RecipeId = 111, ItemId = 111 },
            new Recipe { RecipeId = 112, ItemId = 112 },
            new Recipe { RecipeId = 113, ItemId = 113 },
            new Recipe { RecipeId = 114, ItemId = 114 },
            new Recipe { RecipeId = 115, ItemId = 115 },
            new Recipe { RecipeId = 116, ItemId = 116 },
            new Recipe { RecipeId = 118, ItemId = 118 },
            new Recipe { RecipeId = 119, ItemId = 119 },
            new Recipe { RecipeId = 120, ItemId = 120 },
            new Recipe { RecipeId = 121, ItemId = 121 },
            new Recipe { RecipeId = 122, ItemId = 122 },
            new Recipe { RecipeId = 123, ItemId = 123 },
            new Recipe { RecipeId = 124, ItemId = 124 },
            new Recipe { RecipeId = 125, ItemId = 125 },
            new Recipe { RecipeId = 126, ItemId = 126 },
            new Recipe { RecipeId = 127, ItemId = 127 },
            new Recipe { RecipeId = 128, ItemId = 128 },
            new Recipe { RecipeId = 129, ItemId = 129 },
            new Recipe { RecipeId = 130, ItemId = 130 },
            new Recipe { RecipeId = 131, ItemId = 131 },
            new Recipe { RecipeId = 132, ItemId = 132 },
            new Recipe { RecipeId = 133, ItemId = 133 },
            new Recipe { RecipeId = 134, ItemId = 134 },
            new Recipe { RecipeId = 135, ItemId = 135 },
            new Recipe { RecipeId = 136, ItemId = 136 },
            new Recipe { RecipeId = 137, ItemId = 137 },
            new Recipe { RecipeId = 138, ItemId = 138 },
            new Recipe { RecipeId = 139, ItemId = 139 },
            new Recipe { RecipeId = 140, ItemId = 140 },
            new Recipe { RecipeId = 141, ItemId = 141 },
            new Recipe { RecipeId = 142, ItemId = 142 },
            new Recipe { RecipeId = 143, ItemId = 143 },
            new Recipe { RecipeId = 144, ItemId = 144 },
            new Recipe { RecipeId = 146, ItemId = 146 },
            new Recipe { RecipeId = 147, ItemId = 147 },
            new Recipe { RecipeId = 148, ItemId = 148 },
            new Recipe { RecipeId = 149, ItemId = 149 },
            new Recipe { RecipeId = 150, ItemId = 150 },
            new Recipe { RecipeId = 151, ItemId = 151 },
            new Recipe { RecipeId = 152, ItemId = 152 },
            new Recipe { RecipeId = 153, ItemId = 153 },
            new Recipe { RecipeId = 154, ItemId = 154 },
            new Recipe { RecipeId = 155, ItemId = 155 },
            new Recipe { RecipeId = 156, ItemId = 156 },
            new Recipe { RecipeId = 157, ItemId = 157 },
            new Recipe { RecipeId = 158, ItemId = 158 },
            new Recipe { RecipeId = 159, ItemId = 159 },
            new Recipe { RecipeId = 160, ItemId = 160 },
            new Recipe { RecipeId = 161, ItemId = 161 },
            new Recipe { RecipeId = 162, ItemId = 162 },
            new Recipe { RecipeId = 163, ItemId = 163 },
            new Recipe { RecipeId = 164, ItemId = 164 },
            new Recipe { RecipeId = 165, ItemId = 165 },
            new Recipe { RecipeId = 166, ItemId = 166 },
            new Recipe { RecipeId = 167, ItemId = 167 },
            new Recipe { RecipeId = 168, ItemId = 168 },
            new Recipe { RecipeId = 169, ItemId = 169 }
        );


        modelBuilder.Entity<RecipeItem>().HasData(
            new RecipeItem { RecipeItemId = 1, RecipeId = 1, ItemId = 2, Quantity = 1 },
            new RecipeItem { RecipeItemId = 2, RecipeId = 3, ItemId = 61, Quantity = 10 },
            new RecipeItem { RecipeItemId = 3, RecipeId = 3, ItemId = 20, Quantity = 10 },
            new RecipeItem { RecipeItemId = 4, RecipeId = 5, ItemId = 6, Quantity = 1 },
            new RecipeItem { RecipeItemId = 5, RecipeId = 6, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 6, RecipeId = 6, ItemId = 1, Quantity = 1 },
            new RecipeItem { RecipeItemId = 7, RecipeId = 6, ItemId = 22, Quantity = 2 },
            new RecipeItem { RecipeItemId = 8, RecipeId = 6, ItemId = 42, Quantity = 4 },
            new RecipeItem { RecipeItemId = 9, RecipeId = 11, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 10, RecipeId = 11, ItemId = 38, Quantity = 2 },
            new RecipeItem { RecipeItemId = 11, RecipeId = 11, ItemId = 29, Quantity = 1 },
            new RecipeItem { RecipeItemId = 12, RecipeId = 11, ItemId = 42, Quantity = 1 },
            new RecipeItem { RecipeItemId = 13, RecipeId = 12, ItemId = 11, Quantity = 1 },
            new RecipeItem { RecipeItemId = 14, RecipeId = 13, ItemId = 69, Quantity = 8 },
            new RecipeItem { RecipeItemId = 15, RecipeId = 13, ItemId = 59, Quantity = 4 },
            new RecipeItem { RecipeItemId = 16, RecipeId = 13, ItemId = 74, Quantity = 1 },
            new RecipeItem { RecipeItemId = 17, RecipeId = 14, ItemId = 16, Quantity = 2 },
            new RecipeItem { RecipeItemId = 18, RecipeId = 15, ItemId = 14, Quantity = 1 },
            new RecipeItem { RecipeItemId = 19, RecipeId = 17, ItemId = 14, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 20, RecipeId = 19, ItemId = 4, Quantity = 2 },
            new RecipeItem { RecipeItemId = 21, RecipeId = 21, ItemId = 22, Quantity = 2 },
            new RecipeItem { RecipeItemId = 22, RecipeId = 21, ItemId = 42, Quantity = 2 },
            new RecipeItem { RecipeItemId = 23, RecipeId = 21, ItemId = 17, Quantity = 15 },
            new RecipeItem { RecipeItemId = 24, RecipeId = 21, ItemId = 30, Quantity = 5 },
            new RecipeItem { RecipeItemId = 25, RecipeId = 22, ItemId = 70, Quantity = 2 },
            new RecipeItem { RecipeItemId = 26, RecipeId = 22, ItemId = 74, Quantity = 4 },
            new RecipeItem { RecipeItemId = 27, RecipeId = 26, ItemId = 75, Quantity = 10 },
            new RecipeItem { RecipeItemId = 28, RecipeId = 28, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 29, RecipeId = 30, ItemId = 52, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 30, RecipeId = 32, ItemId = 59, Quantity = 5 },
            new RecipeItem { RecipeItemId = 31, RecipeId = 32, ItemId = 3, Quantity = 1 },
            new RecipeItem { RecipeItemId = 32, RecipeId = 33, ItemId = 70, Quantity = 1 },
            new RecipeItem { RecipeItemId = 33, RecipeId = 33, ItemId = 7, Quantity = 3 },
            new RecipeItem { RecipeItemId = 34, RecipeId = 34, ItemId = 70, Quantity = 5 },
            new RecipeItem { RecipeItemId = 35, RecipeId = 34, ItemId = 3, Quantity = 1 },
            new RecipeItem { RecipeItemId = 36, RecipeId = 36, ItemId = 38, Quantity = 2 },
            new RecipeItem { RecipeItemId = 37, RecipeId = 37, ItemId = 36, Quantity = 0.1 },
            new RecipeItem { RecipeItemId = 38, RecipeId = 42, ItemId = 77, Quantity = 1 },
            new RecipeItem { RecipeItemId = 39, RecipeId = 42, ItemId = 43, Quantity = 1 },
            new RecipeItem { RecipeItemId = 40, RecipeId = 44, ItemId = 45, Quantity = 5 },
            new RecipeItem { RecipeItemId = 41, RecipeId = 46, ItemId = 60, Quantity = 2 },
            new RecipeItem { RecipeItemId = 42, RecipeId = 46, ItemId = 70, Quantity = 1 },
            new RecipeItem { RecipeItemId = 43, RecipeId = 52, ItemId = 29, Quantity = 2 },
            new RecipeItem { RecipeItemId = 44, RecipeId = 53, ItemId = 77, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 45, RecipeId = 54, ItemId = 24, Quantity = 12 },
            new RecipeItem { RecipeItemId = 46, RecipeId = 64, ItemId = 8, Quantity = 1 },
            new RecipeItem { RecipeItemId = 47, RecipeId = 64, ItemId = 38, Quantity = 6 },
            new RecipeItem { RecipeItemId = 48, RecipeId = 65, ItemId = 64, Quantity = 1 },
            new RecipeItem { RecipeItemId = 49, RecipeId = 66, ItemId = 65, Quantity = 0.1 },
            new RecipeItem { RecipeItemId = 50, RecipeId = 67, ItemId = 65, Quantity = 0.01 },
            new RecipeItem { RecipeItemId = 51, RecipeId = 74, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 52, RecipeId = 72, ItemId = 73, Quantity = 5 },
            new RecipeItem { RecipeItemId = 54, RecipeId = 80, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 55, RecipeId = 80, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 56, RecipeId = 80, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 57, RecipeId = 80, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 58, RecipeId = 81, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 59, RecipeId = 81, ItemId = 69, Quantity = 10 },
            new RecipeItem { RecipeItemId = 60, RecipeId = 81, ItemId = 77, Quantity = 20 },
            new RecipeItem { RecipeItemId = 61, RecipeId = 82, ItemId = 61, Quantity = 5 },
            new RecipeItem { RecipeItemId = 62, RecipeId = 82, ItemId = 69, Quantity = 10 },
            new RecipeItem { RecipeItemId = 63, RecipeId = 82, ItemId = 70, Quantity = 5 },
            new RecipeItem { RecipeItemId = 64, RecipeId = 82, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 65, RecipeId = 83, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 66, RecipeId = 83, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 67, RecipeId = 83, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 68, RecipeId = 83, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 69, RecipeId = 84, ItemId = 15, Quantity = 50 },
            new RecipeItem { RecipeItemId = 70, RecipeId = 84, ItemId = 36, Quantity = 2 },
            new RecipeItem { RecipeItemId = 71, RecipeId = 84, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 72, RecipeId = 84, ItemId = 77, Quantity = 60 },
            new RecipeItem { RecipeItemId = 73, RecipeId = 85, ItemId = 15, Quantity = 12 },
            new RecipeItem { RecipeItemId = 74, RecipeId = 85, ItemId = 36, Quantity = 5 },
            new RecipeItem { RecipeItemId = 75, RecipeId = 85, ItemId = 54, Quantity = 10 },
            new RecipeItem { RecipeItemId = 76, RecipeId = 85, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 77, RecipeId = 86, ItemId = 59, Quantity = 4 },
            new RecipeItem { RecipeItemId = 78, RecipeId = 86, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 79, RecipeId = 87, ItemId = 24, Quantity = 12 },
            new RecipeItem { RecipeItemId = 80, RecipeId = 87, ItemId = 68, Quantity = 20 },
            new RecipeItem { RecipeItemId = 81, RecipeId = 87, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 82, RecipeId = 87, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 83, RecipeId = 88, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 84, RecipeId = 88, ItemId = 68, Quantity = 20 },
            new RecipeItem { RecipeItemId = 85, RecipeId = 88, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 86, RecipeId = 88, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 87, RecipeId = 89, ItemId = 15, Quantity = 120 },
            new RecipeItem { RecipeItemId = 88, RecipeId = 89, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 89, RecipeId = 89, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 90, RecipeId = 90, ItemId = 37, Quantity = 120 },
            new RecipeItem { RecipeItemId = 91, RecipeId = 90, ItemId = 39, Quantity = 12 },
            new RecipeItem { RecipeItemId = 92, RecipeId = 90, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 93, RecipeId = 90, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 94, RecipeId = 91, ItemId = 22, Quantity = 10 },
            new RecipeItem { RecipeItemId = 95, RecipeId = 91, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 96, RecipeId = 91, ItemId = 37, Quantity = 120 },
            new RecipeItem { RecipeItemId = 97, RecipeId = 91, ItemId = 54, Quantity = 24 },
            new RecipeItem { RecipeItemId = 98, RecipeId = 91, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 99, RecipeId = 91, ItemId = 77, Quantity = 20 },
            new RecipeItem { RecipeItemId = 100, RecipeId = 92, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 101, RecipeId = 92, ItemId = 37, Quantity = 8 },
            new RecipeItem { RecipeItemId = 102, RecipeId = 92, ItemId = 53, Quantity = 50 },
            new RecipeItem { RecipeItemId = 103, RecipeId = 92, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 104, RecipeId = 92, ItemId = 69, Quantity = 40 },
            new RecipeItem { RecipeItemId = 105, RecipeId = 93, ItemId = 15, Quantity = 40 },
            new RecipeItem { RecipeItemId = 106, RecipeId = 93, ItemId = 22, Quantity = 6 },
            new RecipeItem { RecipeItemId = 107, RecipeId = 93, ItemId = 36, Quantity = 24 },
            new RecipeItem { RecipeItemId = 108, RecipeId = 93, ItemId = 53, Quantity = 10 },
            new RecipeItem { RecipeItemId = 109, RecipeId = 93, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 110, RecipeId = 94, ItemId = 22, Quantity = 8 },
            new RecipeItem { RecipeItemId = 111, RecipeId = 94, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 112, RecipeId = 94, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 113, RecipeId = 94, ItemId = 67, Quantity = 40 },
            new RecipeItem { RecipeItemId = 114, RecipeId = 94, ItemId = 77, Quantity = 6 },
            new RecipeItem { RecipeItemId = 115, RecipeId = 95, ItemId = 15, Quantity = 40 },
            new RecipeItem { RecipeItemId = 116, RecipeId = 95, ItemId = 22, Quantity = 6 },
            new RecipeItem { RecipeItemId = 117, RecipeId = 95, ItemId = 36, Quantity = 24 },
            new RecipeItem { RecipeItemId = 118, RecipeId = 95, ItemId = 53, Quantity = 10 },
            new RecipeItem { RecipeItemId = 119, RecipeId = 95, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 120, RecipeId = 96, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 121, RecipeId = 96, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 122, RecipeId = 96, ItemId = 13, Quantity = 30 },
            new RecipeItem { RecipeItemId = 123, RecipeId = 96, ItemId = 21, Quantity = 30 },
            new RecipeItem { RecipeItemId = 124, RecipeId = 96, ItemId = 67, Quantity = 30 },
            new RecipeItem { RecipeItemId = 130, RecipeId = 97, ItemId = 1, Quantity = 30 },
            new RecipeItem { RecipeItemId = 131, RecipeId = 97, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 132, RecipeId = 97, ItemId = 21, Quantity = 60 },
            new RecipeItem { RecipeItemId = 133, RecipeId = 97, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 134, RecipeId = 97, ItemId = 164, Quantity = 3 },
            new RecipeItem { RecipeItemId = 135, RecipeId = 164, ItemId = 72, Quantity = 3 },
            new RecipeItem { RecipeItemId = 136, RecipeId = 98, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 137, RecipeId = 98, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 138, RecipeId = 98, ItemId = 28, Quantity = 10 },
            new RecipeItem { RecipeItemId = 139, RecipeId = 98, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 140, RecipeId = 98, ItemId = 65, Quantity = 20 },
            new RecipeItem { RecipeItemId = 141, RecipeId = 99, ItemId = 13, Quantity = 15 },
            new RecipeItem { RecipeItemId = 142, RecipeId = 99, ItemId = 21, Quantity = 8 },
            new RecipeItem { RecipeItemId = 143, RecipeId = 99, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 144, RecipeId = 99, ItemId = 67, Quantity = 18 },
            new RecipeItem { RecipeItemId = 145, RecipeId = 100, ItemId = 13, Quantity = 25 },
            new RecipeItem { RecipeItemId = 146, RecipeId = 100, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 147, RecipeId = 100, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 148, RecipeId = 100, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 149, RecipeId = 100, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 150, RecipeId = 101, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 151, RecipeId = 101, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 152, RecipeId = 101, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 153, RecipeId = 101, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 154, RecipeId = 101, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 155, RecipeId = 102, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 156, RecipeId = 102, ItemId = 13, Quantity = 100 },
            new RecipeItem { RecipeItemId = 157, RecipeId = 102, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 158, RecipeId = 102, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 159, RecipeId = 102, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 160, RecipeId = 103, ItemId = 39, Quantity = 12 },
            new RecipeItem { RecipeItemId = 161, RecipeId = 103, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 162, RecipeId = 103, ItemId = 69, Quantity = 80 },
            new RecipeItem { RecipeItemId = 163, RecipeId = 103, ItemId = 77, Quantity = 12 },
            new RecipeItem { RecipeItemId = 164, RecipeId = 104, ItemId = 13, Quantity = 20 },
            new RecipeItem { RecipeItemId = 165, RecipeId = 104, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 166, RecipeId = 104, ItemId = 36, Quantity = 12 },
            new RecipeItem { RecipeItemId = 167, RecipeId = 104, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 168, RecipeId = 105, ItemId = 13, Quantity = 80 },
            new RecipeItem { RecipeItemId = 169, RecipeId = 105, ItemId = 21, Quantity = 60 },
            new RecipeItem { RecipeItemId = 170, RecipeId = 105, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 171, RecipeId = 105, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 172, RecipeId = 105, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 173, RecipeId = 107, ItemId = 24, Quantity = 8 },
            new RecipeItem { RecipeItemId = 174, RecipeId = 107, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 175, RecipeId = 107, ItemId = 69, Quantity = 24 },
            new RecipeItem { RecipeItemId = 176, RecipeId = 108, ItemId = 24, Quantity = 50 },
            new RecipeItem { RecipeItemId = 177, RecipeId = 108, ItemId = 68, Quantity = 25 },
            new RecipeItem { RecipeItemId = 178, RecipeId = 108, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 179, RecipeId = 109, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 180, RecipeId = 109, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 181, RecipeId = 110, ItemId = 69, Quantity = 120 },
            new RecipeItem { RecipeItemId = 182, RecipeId = 110, ItemId = 77, Quantity = 30 },
            new RecipeItem { RecipeItemId = 183, RecipeId = 111, ItemId = 24, Quantity = 8 },
            new RecipeItem { RecipeItemId = 184, RecipeId = 111, ItemId = 36, Quantity = 4 },
            new RecipeItem { RecipeItemId = 185, RecipeId = 111, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 186, RecipeId = 111, ItemId = 69, Quantity = 24 },
            new RecipeItem { RecipeItemId = 187, RecipeId = 112, ItemId = 14, Quantity = 8 },
            new RecipeItem { RecipeItemId = 188, RecipeId = 112, ItemId = 22, Quantity = 10 },
            new RecipeItem { RecipeItemId = 189, RecipeId = 112, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 190, RecipeId = 113, ItemId = 15, Quantity = 20 },
            new RecipeItem { RecipeItemId = 191, RecipeId = 113, ItemId = 22, Quantity = 20 },
            new RecipeItem { RecipeItemId = 192, RecipeId = 113, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 193, RecipeId = 113, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 194, RecipeId = 114, ItemId = 15, Quantity = 4 },
            new RecipeItem { RecipeItemId = 195, RecipeId = 114, ItemId = 22, Quantity = 20 },
            new RecipeItem { RecipeItemId = 196, RecipeId = 114, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 197, RecipeId = 114, ItemId = 65, Quantity = 24 },
            new RecipeItem { RecipeItemId = 198, RecipeId = 114, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 199, RecipeId = 115, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 200, RecipeId = 115, ItemId = 12, Quantity = 2 },
            new RecipeItem { RecipeItemId = 201, RecipeId = 115, ItemId = 13, Quantity = 10 },
            new RecipeItem { RecipeItemId = 202, RecipeId = 115, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 203, RecipeId = 115, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 204, RecipeId = 116, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 205, RecipeId = 116, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 206, RecipeId = 116, ItemId = 17, Quantity = 8 },
            new RecipeItem { RecipeItemId = 207, RecipeId = 116, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 208, RecipeId = 116, ItemId = 28, Quantity = 12 },
            new RecipeItem { RecipeItemId = 209, RecipeId = 116, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 210, RecipeId = 118, ItemId = 7, Quantity = 25 },
            new RecipeItem { RecipeItemId = 211, RecipeId = 118, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 212, RecipeId = 118, ItemId = 69, Quantity = 25 },
            new RecipeItem { RecipeItemId = 213, RecipeId = 118, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 214, RecipeId = 119, ItemId = 15, Quantity = 4 },
            new RecipeItem { RecipeItemId = 215, RecipeId = 119, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 216, RecipeId = 119, ItemId = 39, Quantity = 24 },
            new RecipeItem { RecipeItemId = 217, RecipeId = 119, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 218, RecipeId = 119, ItemId = 77, Quantity = 40 },
            new RecipeItem { RecipeItemId = 219, RecipeId = 120, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 220, RecipeId = 120, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 221, RecipeId = 120, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 222, RecipeId = 120, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 223, RecipeId = 121, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 224, RecipeId = 121, ItemId = 5, Quantity = 10 },
            new RecipeItem { RecipeItemId = 225, RecipeId = 121, ItemId = 21, Quantity = 15 },
            new RecipeItem { RecipeItemId = 226, RecipeId = 121, ItemId = 44, Quantity = 20 },
            new RecipeItem { RecipeItemId = 227, RecipeId = 121, ItemId = 67, Quantity = 15 },
            new RecipeItem { RecipeItemId = 228, RecipeId = 122, ItemId = 77, Quantity = 100 },
            new RecipeItem { RecipeItemId = 229, RecipeId = 123, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 230, RecipeId = 124, ItemId = 4, Quantity = 10 },
            new RecipeItem { RecipeItemId = 231, RecipeId = 124, ItemId = 24, Quantity = 24 },
            new RecipeItem { RecipeItemId = 232, RecipeId = 124, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 233, RecipeId = 124, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 234, RecipeId = 125, ItemId = 4, Quantity = 8 },
            new RecipeItem { RecipeItemId = 235, RecipeId = 125, ItemId = 39, Quantity = 24 },
            new RecipeItem { RecipeItemId = 236, RecipeId = 125, ItemId = 77, Quantity = 18 },
            new RecipeItem { RecipeItemId = 242, RecipeId = 126, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 243, RecipeId = 126, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 244, RecipeId = 126, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 245, RecipeId = 126, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 246, RecipeId = 126, ItemId = 65, Quantity = 15 },
            new RecipeItem { RecipeItemId = 247, RecipeId = 127, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 248, RecipeId = 127, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 249, RecipeId = 127, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 250, RecipeId = 127, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 251, RecipeId = 127, ItemId = 65, Quantity = 15 },
            new RecipeItem { RecipeItemId = 252, RecipeId = 128, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 253, RecipeId = 128, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 254, RecipeId = 128, ItemId = 21, Quantity = 35 },
            new RecipeItem { RecipeItemId = 255, RecipeId = 128, ItemId = 28, Quantity = 15 },
            new RecipeItem { RecipeItemId = 256, RecipeId = 128, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 257, RecipeId = 129, ItemId = 24, Quantity = 20 },
            new RecipeItem { RecipeItemId = 258, RecipeId = 129, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 259, RecipeId = 129, ItemId = 70, Quantity = 8 },
            new RecipeItem { RecipeItemId = 260, RecipeId = 130, ItemId = 14, Quantity = 4 },
            new RecipeItem { RecipeItemId = 261, RecipeId = 130, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 267, RecipeId = 165, ItemId = 1, Quantity = 6 },
            new RecipeItem { RecipeItemId = 268, RecipeId = 165, ItemId = 17, Quantity = 10 },
            new RecipeItem { RecipeItemId = 269, RecipeId = 165, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 270, RecipeId = 165, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 271, RecipeId = 165, ItemId = 30, Quantity = 10 },
            new RecipeItem { RecipeItemId = 272, RecipeId = 143, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 273, RecipeId = 143, ItemId = 12, Quantity = 18 },
            new RecipeItem { RecipeItemId = 274, RecipeId = 143, ItemId = 21, Quantity = 30 },
            new RecipeItem { RecipeItemId = 275, RecipeId = 143, ItemId = 28, Quantity = 60 },
            new RecipeItem { RecipeItemId = 276, RecipeId = 143, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 277, RecipeId = 166, ItemId = 14, Quantity = 10 },
            new RecipeItem { RecipeItemId = 278, RecipeId = 166, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 279, RecipeId = 166, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 280, RecipeId = 166, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 281, RecipeId = 166, ItemId = 65, Quantity = 12 },
            new RecipeItem { RecipeItemId = 282, RecipeId = 167, ItemId = 1, Quantity = 25 },
            new RecipeItem { RecipeItemId = 283, RecipeId = 167, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 284, RecipeId = 167, ItemId = 21, Quantity = 15 },
            new RecipeItem { RecipeItemId = 285, RecipeId = 167, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 286, RecipeId = 167, ItemId = 72, Quantity = 8 },
            new RecipeItem { RecipeItemId = 287, RecipeId = 131, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 288, RecipeId = 131, ItemId = 39, Quantity = 8 },
            new RecipeItem { RecipeItemId = 289, RecipeId = 131, ItemId = 70, Quantity = 8 },
            new RecipeItem { RecipeItemId = 290, RecipeId = 131, ItemId = 77, Quantity = 4 },
            new RecipeItem { RecipeItemId = 291, RecipeId = 132, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 292, RecipeId = 132, ItemId = 28, Quantity = 6 },
            new RecipeItem { RecipeItemId = 293, RecipeId = 132, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 294, RecipeId = 133, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 295, RecipeId = 133, ItemId = 28, Quantity = 6 },
            new RecipeItem { RecipeItemId = 296, RecipeId = 133, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 297, RecipeId = 134, ItemId = 1, Quantity = 10 },
            new RecipeItem { RecipeItemId = 298, RecipeId = 134, ItemId = 12, Quantity = 5 },
            new RecipeItem { RecipeItemId = 299, RecipeId = 134, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 300, RecipeId = 134, ItemId = 28, Quantity = 5 },
            new RecipeItem { RecipeItemId = 301, RecipeId = 135, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 302, RecipeId = 135, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 303, RecipeId = 135, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 304, RecipeId = 135, ItemId = 28, Quantity = 5 },
            new RecipeItem { RecipeItemId = 305, RecipeId = 136, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 306, RecipeId = 136, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 307, RecipeId = 136, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 308, RecipeId = 136, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 309, RecipeId = 137, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 310, RecipeId = 137, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 311, RecipeId = 137, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 312, RecipeId = 137, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 313, RecipeId = 138, ItemId = 39, Quantity = 8 },
            new RecipeItem { RecipeItemId = 314, RecipeId = 138, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 315, RecipeId = 138, ItemId = 69, Quantity = 60 },
            new RecipeItem { RecipeItemId = 316, RecipeId = 138, ItemId = 77, Quantity = 24 },
            new RecipeItem { RecipeItemId = 317, RecipeId = 139, ItemId = 13, Quantity = 20 },
            new RecipeItem { RecipeItemId = 318, RecipeId = 139, ItemId = 21, Quantity = 4 },
            new RecipeItem { RecipeItemId = 319, RecipeId = 139, ItemId = 65, Quantity = 24 },
            new RecipeItem { RecipeItemId = 320, RecipeId = 139, ItemId = 67, Quantity = 16 },
            new RecipeItem { RecipeItemId = 321, RecipeId = 140, ItemId = 13, Quantity = 12 },
            new RecipeItem { RecipeItemId = 322, RecipeId = 140, ItemId = 14, Quantity = 8 },
            new RecipeItem { RecipeItemId = 323, RecipeId = 140, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 324, RecipeId = 140, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 325, RecipeId = 141, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 326, RecipeId = 141, ItemId = 13, Quantity = 100 },
            new RecipeItem { RecipeItemId = 327, RecipeId = 141, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 328, RecipeId = 141, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 329, RecipeId = 141, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 330, RecipeId = 142, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 331, RecipeId = 142, ItemId = 21, Quantity = 12 },
            new RecipeItem { RecipeItemId = 332, RecipeId = 142, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 333, RecipeId = 142, ItemId = 65, Quantity = 20 },
            new RecipeItem { RecipeItemId = 334, RecipeId = 142, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 335, RecipeId = 144, ItemId = 15, Quantity = 50 },
            new RecipeItem { RecipeItemId = 336, RecipeId = 144, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 337, RecipeId = 144, ItemId = 42, Quantity = 25 },
            new RecipeItem { RecipeItemId = 338, RecipeId = 144, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 339, RecipeId = 144, ItemId = 69, Quantity = 50 },
            new RecipeItem { RecipeItemId = 340, RecipeId = 144, ItemId = 77, Quantity = 100 },
            new RecipeItem { RecipeItemId = 341, RecipeId = 147, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 342, RecipeId = 147, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 343, RecipeId = 147, ItemId = 30, Quantity = 50 },
            new RecipeItem { RecipeItemId = 344, RecipeId = 147, ItemId = 36, Quantity = 12 },
            new RecipeItem { RecipeItemId = 345, RecipeId = 147, ItemId = 37, Quantity = 8 },
            new RecipeItem { RecipeItemId = 346, RecipeId = 148, ItemId = 15, Quantity = 10 },
            new RecipeItem { RecipeItemId = 347, RecipeId = 148, ItemId = 30, Quantity = 25 },
            new RecipeItem { RecipeItemId = 348, RecipeId = 148, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 349, RecipeId = 149, ItemId = 12, Quantity = 12 },
            new RecipeItem { RecipeItemId = 350, RecipeId = 149, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 351, RecipeId = 149, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 352, RecipeId = 149, ItemId = 65, Quantity = 12 },
            new RecipeItem { RecipeItemId = 353, RecipeId = 149, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 354, RecipeId = 150, ItemId = 21, Quantity = 5 },
            new RecipeItem { RecipeItemId = 355, RecipeId = 150, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 357, RecipeId = 151, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 358, RecipeId = 151, ItemId = 77, Quantity = 60 },
            new RecipeItem { RecipeItemId = 359, RecipeId = 152, ItemId = 36, Quantity = 6 },
            new RecipeItem { RecipeItemId = 360, RecipeId = 152, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 361, RecipeId = 152, ItemId = 77, Quantity = 40 },
            new RecipeItem { RecipeItemId = 362, RecipeId = 153, ItemId = 37, Quantity = 18 },
            new RecipeItem { RecipeItemId = 363, RecipeId = 153, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 364, RecipeId = 153, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 365, RecipeId = 154, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 366, RecipeId = 154, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 367, RecipeId = 155, ItemId = 14, Quantity = 10 },
            new RecipeItem { RecipeItemId = 368, RecipeId = 156, ItemId = 17, Quantity = 4 },
            new RecipeItem { RecipeItemId = 369, RecipeId = 156, ItemId = 22, Quantity = 4 },
            new RecipeItem { RecipeItemId = 370, RecipeId = 156, ItemId = 65, Quantity = 2 },
            new RecipeItem { RecipeItemId = 371, RecipeId = 157, ItemId = 57, Quantity = 1 },
            new RecipeItem { RecipeItemId = 372, RecipeId = 157, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 373, RecipeId = 157, ItemId = 69, Quantity = 4 },
            new RecipeItem { RecipeItemId = 374, RecipeId = 158, ItemId = 58, Quantity = 1 },
            new RecipeItem { RecipeItemId = 375, RecipeId = 158, ItemId = 151, Quantity = 1 },
            new RecipeItem { RecipeItemId = 376, RecipeId = 159, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 377, RecipeId = 159, ItemId = 70, Quantity = 10 },
            new RecipeItem { RecipeItemId = 378, RecipeId = 159, ItemId = 77, Quantity = 8 },
            new RecipeItem { RecipeItemId = 379, RecipeId = 160, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 380, RecipeId = 160, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 381, RecipeId = 160, ItemId = 36, Quantity = 10 },
            new RecipeItem { RecipeItemId = 382, RecipeId = 160, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 383, RecipeId = 160, ItemId = 70, Quantity = 12 },
            new RecipeItem { RecipeItemId = 384, RecipeId = 161, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 385, RecipeId = 161, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 386, RecipeId = 161, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 387, RecipeId = 161, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 388, RecipeId = 161, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 389, RecipeId = 161, ItemId = 67, Quantity = 25 },
            new RecipeItem { RecipeItemId = 390, RecipeId = 168, ItemId = 49, Quantity = 1 },
            new RecipeItem { RecipeItemId = 391, RecipeId = 162, ItemId = 49, Quantity = 1 },
            new RecipeItem { RecipeItemId = 392, RecipeId = 162, ItemId = 168, Quantity = 2 },
            new RecipeItem { RecipeItemId = 393, RecipeId = 163, ItemId = 46, Quantity = 2 },
            new RecipeItem { RecipeItemId = 394, RecipeId = 163, ItemId = 162, Quantity = 1 },
            new RecipeItem { RecipeItemId = 395, RecipeId = 146, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 396, RecipeId = 146, ItemId = 21, Quantity = 6 },
            new RecipeItem { RecipeItemId = 397, RecipeId = 146, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 398, RecipeId = 146, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 399, RecipeId = 146, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 400, RecipeId = 169, ItemId = 17, Quantity = 70 },
            new RecipeItem { RecipeItemId = 401, RecipeId = 169, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 402, RecipeId = 169, ItemId = 28, Quantity = 10 },
            new RecipeItem { RecipeItemId = 403, RecipeId = 169, ItemId = 164, Quantity = 2 }
        );
    }
}
