using Icarus_Item_Calculator.Models;
using Microsoft.EntityFrameworkCore;

namespace Icarus_Item_Calculator.SeedData
{
    public static class ItemSeedData
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Item>().HasData(
                new Item { ItemId = 1, Name = "Aluminium Ingot", IsBaseItem = false },
                new Item { ItemId = 2, Name = "Aluminum Ore", IsBaseItem = true },
                new Item { ItemId = 3, Name = "Basic Fertilizer", IsBaseItem = false },
                new Item { ItemId = 4, Name = "Bone", IsBaseItem = true },
                new Item { ItemId = 5, Name = "Carbon Fiber", IsBaseItem = false },
                new Item { ItemId = 6, Name = "Carbon Paste", IsBaseItem = false },
                new Item { ItemId = 7, Name = "Charcoal", IsBaseItem = true },
                new Item { ItemId = 8, Name = "Coal Ore", IsBaseItem = true },
                new Item { ItemId = 9, Name = "Cocoa Seed", IsBaseItem = true },
                new Item { ItemId = 10, Name = "Coffee Bean", IsBaseItem = true },
                new Item { ItemId = 11, Name = "Composite Paste", IsBaseItem = false },
                new Item { ItemId = 12, Name = "Composites", IsBaseItem = false },
                new Item { ItemId = 13, Name = "Concrete Mix", IsBaseItem = false },
                new Item { ItemId = 14, Name = "Copper Ingot", IsBaseItem = false },
                new Item { ItemId = 15, Name = "Copper Nail", IsBaseItem = false },
                new Item { ItemId = 16, Name = "Copper Ore", IsBaseItem = true },
                new Item { ItemId = 17, Name = "Copper Wire", IsBaseItem = false },
                new Item { ItemId = 18, Name = "Corn", IsBaseItem = true },
                new Item { ItemId = 19, Name = "Crushed Bone", IsBaseItem = false },
                new Item { ItemId = 20, Name = "Dirt", IsBaseItem = true },
                new Item { ItemId = 21, Name = "Electronics", IsBaseItem = false },
                new Item { ItemId = 22, Name = "Epoxy", IsBaseItem = false },
                new Item { ItemId = 23, Name = "Exotics", IsBaseItem = true },
                new Item { ItemId = 24, Name = "Fiber", IsBaseItem = true },
                new Item { ItemId = 25, Name = "Fish Chunks", IsBaseItem = true },
                new Item { ItemId = 26, Name = "Flour", IsBaseItem = false },
                new Item { ItemId = 27, Name = "Fur", IsBaseItem = true },
                new Item { ItemId = 28, Name = "Glass", IsBaseItem = false },
                new Item { ItemId = 29, Name = "Gold Ore", IsBaseItem = true },
                new Item { ItemId = 30, Name = "Gold Wire", IsBaseItem = false },
                new Item { ItemId = 31, Name = "Gorse Flower", IsBaseItem = true },
                new Item { ItemId = 32, Name = "Growth Fertilizer", IsBaseItem = false },
                new Item { ItemId = 33, Name = "Gunpowder", IsBaseItem = false },
                new Item { ItemId = 34, Name = "High-Quality Fertilizer", IsBaseItem = false },
                new Item { ItemId = 35, Name = "Ice", IsBaseItem = true },
                new Item { ItemId = 36, Name = "Iron Ingot", IsBaseItem = false },
                new Item { ItemId = 37, Name = "Iron Nail", IsBaseItem = false },
                new Item { ItemId = 38, Name = "Iron Ore", IsBaseItem = true },
                new Item { ItemId = 39, Name = "Leather", IsBaseItem = true },
                new Item { ItemId = 40, Name = "Lily", IsBaseItem = true },
                new Item { ItemId = 41, Name = "Mammoth Tusk", IsBaseItem = true },
                new Item { ItemId = 42, Name = "Organic Resin", IsBaseItem = false },
                new Item { ItemId = 43, Name = "Oxite", IsBaseItem = true },
                new Item { ItemId = 44, Name = "Platinum Ingot", IsBaseItem = false },
                new Item { ItemId = 45, Name = "Platinum Ore", IsBaseItem = true },
                new Item { ItemId = 46, Name = "Poison Paste", IsBaseItem = false },
                new Item { ItemId = 47, Name = "Poison Sack", IsBaseItem = true },
                new Item { ItemId = 48, Name = "Polar Bear Pelt", IsBaseItem = true },
                new Item { ItemId = 49, Name = "Raw Meat", IsBaseItem = true },
                new Item { ItemId = 50, Name = "Raw Prime Meat", IsBaseItem = true },
                new Item { ItemId = 51, Name = "Reed Flower", IsBaseItem = true },
                new Item { ItemId = 52, Name = "Refined Gold", IsBaseItem = false },
                new Item { ItemId = 53, Name = "Refined Wood", IsBaseItem = false },
                new Item { ItemId = 54, Name = "Rope", IsBaseItem = false },
                new Item { ItemId = 55, Name = "Salt", IsBaseItem = true },
                new Item { ItemId = 56, Name = "Sandworm Scale", IsBaseItem = true },
                new Item { ItemId = 57, Name = "Scorpion Pincer", IsBaseItem = true },
                new Item { ItemId = 58, Name = "Scorpion Tail", IsBaseItem = true },
                new Item { ItemId = 59, Name = "Silica Ore", IsBaseItem = true },
                new Item { ItemId = 60, Name = "Spoiled Meat", IsBaseItem = true },
                new Item { ItemId = 61, Name = "Spoiled Plants", IsBaseItem = true },
                new Item { ItemId = 62, Name = "Sponge", IsBaseItem = true },
                new Item { ItemId = 63, Name = "Squash", IsBaseItem = true },
                new Item { ItemId = 64, Name = "Steel Bloom", IsBaseItem = false },
                new Item { ItemId = 65, Name = "Steel Ingot", IsBaseItem = false },
                new Item { ItemId = 66, Name = "Steel Rebar", IsBaseItem = false },
                new Item { ItemId = 67, Name = "Steel Screw", IsBaseItem = false },
                new Item { ItemId = 68, Name = "Stick", IsBaseItem = false },
                new Item { ItemId = 69, Name = "Stone", IsBaseItem = true },
                new Item { ItemId = 70, Name = "Sulfur", IsBaseItem = true },
                new Item { ItemId = 71, Name = "Tea", IsBaseItem = true },
                new Item { ItemId = 72, Name = "Titanium Ingot", IsBaseItem = false },
                new Item { ItemId = 73, Name = "Titanium Ore", IsBaseItem = true },
                new Item { ItemId = 74, Name = "Tree Sap", IsBaseItem = false },
                new Item { ItemId = 75, Name = "Wheat", IsBaseItem = true },
                new Item { ItemId = 76, Name = "Wild Berry", IsBaseItem = true },
                new Item { ItemId = 77, Name = "Wood", IsBaseItem = true },
                new Item { ItemId = 78, Name = "Worm Scale", IsBaseItem = true },
                new Item { ItemId = 79, Name = "Yeast", IsBaseItem = true },
                new Item { ItemId = 80, Name = "Crafting Bench", IsBaseItem = false },
                new Item { ItemId = 81, Name = "Anvil Bench", IsBaseItem = false },
                new Item { ItemId = 82, Name = "Wood Composter", IsBaseItem = false },
                new Item { ItemId = 83, Name = "Skinning Bench", IsBaseItem = false },
                new Item { ItemId = 84, Name = "Trophy Bench", IsBaseItem = false },
                new Item { ItemId = 85, Name = "Basic Fishing Bench", IsBaseItem = false },
                new Item { ItemId = 86, Name = "Mortar and Pestle", IsBaseItem = false },
                new Item { ItemId = 87, Name = "Herbalism Bench", IsBaseItem = false },
                new Item { ItemId = 88, Name = "Textiles Bench", IsBaseItem = false },
                new Item { ItemId = 89, Name = "Carpentry Bench", IsBaseItem = false },
                new Item { ItemId = 90, Name = "Masonry Bench", IsBaseItem = false },
                new Item { ItemId = 91, Name = "Machining Bench", IsBaseItem = false },
                new Item { ItemId = 92, Name = "Cement Mixer", IsBaseItem = false },
                new Item { ItemId = 93, Name = "Glassworking Bench", IsBaseItem = false },
                new Item { ItemId = 94, Name = "Advanced Textiles Bench", IsBaseItem = false },
                new Item { ItemId = 95, Name = "Alteration Bench", IsBaseItem = false },
                new Item { ItemId = 96, Name = "Fabricator", IsBaseItem = false },
                new Item { ItemId = 97, Name = "Material Processor", IsBaseItem = false },
                new Item { ItemId = 98, Name = "Chemistry Bench", IsBaseItem = false },
                new Item { ItemId = 99, Name = "Electric Textiles Bench", IsBaseItem = false },
                new Item { ItemId = 100, Name = "Advanced Alteration Bench", IsBaseItem = false },
                new Item { ItemId = 101, Name = "Electric Carpentry Bench", IsBaseItem = false },
                new Item { ItemId = 102, Name = "Electric Masonry Bench", IsBaseItem = false },
                new Item { ItemId = 103, Name = "Stone Furnace", IsBaseItem = false },
                new Item { ItemId = 104, Name = "Concrete Furnace", IsBaseItem = false },
                new Item { ItemId = 105, Name = "Electric Furnace", IsBaseItem = false },
                new Item { ItemId = 106, Name = "MXC Furnace", IsBaseItem = false },
                new Item { ItemId = 107, Name = "Campfire", IsBaseItem = false },
                new Item { ItemId = 108, Name = "Drying Rack", IsBaseItem = false },
                new Item { ItemId = 109, Name = "Firepit", IsBaseItem = false },
                new Item { ItemId = 110, Name = "Fireplace", IsBaseItem = false },
                new Item { ItemId = 111, Name = "Cooking Station", IsBaseItem = false },
                new Item { ItemId = 112, Name = "Potbelly Stove", IsBaseItem = false },
                new Item { ItemId = 113, Name = "Kitchen Bench", IsBaseItem = false },
                new Item { ItemId = 114, Name = "Biofuel Stove", IsBaseItem = false },
                new Item { ItemId = 115, Name = "Marble Kitchen Bench", IsBaseItem = false },
                new Item { ItemId = 116, Name = "Electric Stove", IsBaseItem = false },
                new Item { ItemId = 117, Name = "MXC Campfire", IsBaseItem = false },
                new Item { ItemId = 118, Name = "Salting Station", IsBaseItem = false },
                new Item { ItemId = 119, Name = "Ice Box", IsBaseItem = false },
                new Item { ItemId = 120, Name = "Refrigerator", IsBaseItem = false },
                new Item { ItemId = 121, Name = "Deep Freeze", IsBaseItem = false },
                new Item { ItemId = 122, Name = "Wood Pile", IsBaseItem = false },
                new Item { ItemId = 123, Name = "Stone Pile", IsBaseItem = false },
                new Item { ItemId = 124, Name = "Oxidizer", IsBaseItem = false },
                new Item { ItemId = 125, Name = "Oxite Dissolver", IsBaseItem = false },
                new Item { ItemId = 126, Name = "Biofuel Oxite Dissolver", IsBaseItem = false },
                new Item { ItemId = 127, Name = "Dehumidifier", IsBaseItem = false },
                new Item { ItemId = 128, Name = "Electric Dehumidifier", IsBaseItem = false },
                new Item { ItemId = 129, Name = "Floor Torch", IsBaseItem = false },
                new Item { ItemId = 130, Name = "Brazier", IsBaseItem = false },
                new Item { ItemId = 131, Name = "Wall Torch", IsBaseItem = false },
                new Item { ItemId = 132, Name = "Basic Wall Light", IsBaseItem = false },
                new Item { ItemId = 133, Name = "Basic Ceiling Light", IsBaseItem = false },
                new Item { ItemId = 134, Name = "Directional Worklamp", IsBaseItem = false },
                new Item { ItemId = 135, Name = "Omnidirectional Worklamp", IsBaseItem = false },
                new Item { ItemId = 136, Name = "Heavy Heater", IsBaseItem = false },
                new Item { ItemId = 137, Name = "Heavy Air Conditioner", IsBaseItem = false },
                new Item { ItemId = 138, Name = "Rain Reservoir", IsBaseItem = false },
                new Item { ItemId = 139, Name = "Electric Water Pump", IsBaseItem = false },
                new Item { ItemId = 140, Name = "Biofuel Composter", IsBaseItem = false },
                new Item { ItemId = 141, Name = "Electric Composter", IsBaseItem = false },
                new Item { ItemId = 142, Name = "Biofuel Generator", IsBaseItem = false },
                new Item { ItemId = 143, Name = "Solar Panel", IsBaseItem = false },
                new Item { ItemId = 144, Name = "Water Wheel", IsBaseItem = false },
                new Item { ItemId = 145, Name = "Wind Turbine", IsBaseItem = false },
                new Item { ItemId = 146, Name = "Portable Biofuel Generator", IsBaseItem = false },
                new Item { ItemId = 147, Name = "Biofuel Radar", IsBaseItem = false },
                new Item { ItemId = 148, Name = "Biofuel Extractor", IsBaseItem = false },
                new Item { ItemId = 149, Name = "Electric Radar", IsBaseItem = false },
                new Item { ItemId = 150, Name = "Electric Extractor", IsBaseItem = false },
                new Item { ItemId = 151, Name = "Medium Wood Hedgehog", IsBaseItem = false },
                new Item { ItemId = 152, Name = "Wood Gate Fortification", IsBaseItem = false },
                new Item { ItemId = 153, Name = "Wood Wall Fortification", IsBaseItem = false },
                new Item { ItemId = 154, Name = "Wood Spikes Fortification", IsBaseItem = false },
                new Item { ItemId = 155, Name = "Lightning Rod", IsBaseItem = false },
                new Item { ItemId = 156, Name = "Water Sprinkler", IsBaseItem = false },
                new Item { ItemId = 157, Name = "Scorpion Pincer Trap", IsBaseItem = false },
                new Item { ItemId = 158, Name = "Scorpion Hedgehog", IsBaseItem = false },
                new Item { ItemId = 159, Name = "Wood Crop Plot", IsBaseItem = false },
                new Item { ItemId = 160, Name = "Iron Crop Plot", IsBaseItem = false },
                new Item { ItemId = 161, Name = "Hydroponic Crop Plot", IsBaseItem = false },
                new Item { ItemId = 162, Name = "Animal Bait", IsBaseItem = false },
                new Item { ItemId = 163, Name = "Poisoned Animal Bait", IsBaseItem = false },
                new Item { ItemId = 164, Name = "Titanium Plate", IsBaseItem = false },
                new Item { ItemId = 165, Name = "Flow Meter", IsBaseItem = false },
                new Item { ItemId = 166, Name = "Biofuel Deep-Mining Drill", IsBaseItem = false },
                new Item { ItemId = 167, Name = "Electric Deep-Mining Drill", IsBaseItem = false },
                new Item { ItemId = 168, Name = "Animal Fat", IsBaseItem = false },
                new Item { ItemId = 169, Name = "Electrolytic Oxygen Synthesizer", IsBaseItem = false }
            );
        }
    }
}