using Icarus_Item_Calculator.Models;
using Microsoft.EntityFrameworkCore;

namespace Icarus_Item_Calculator.SeedData
{
    public static class RecipeSeedData
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Recipe>().HasData(
                new Recipe { RecipeId = 1, ItemId = 1 },
                new Recipe { RecipeId = 2, ItemId = 3 },
                new Recipe { RecipeId = 3, ItemId = 3 },
                new Recipe { RecipeId = 4, ItemId = 4 },
                new Recipe { RecipeId = 5, ItemId = 5 },
                new Recipe { RecipeId = 6, ItemId = 6 },
                new Recipe { RecipeId = 11, ItemId = 11 },
                new Recipe { RecipeId = 12, ItemId = 12 },
                new Recipe { RecipeId = 13, ItemId = 13 },
                new Recipe { RecipeId = 14, ItemId = 14 },
                new Recipe { RecipeId = 15, ItemId = 15 },
                new Recipe { RecipeId = 17, ItemId = 17 },
                new Recipe { RecipeId = 19, ItemId = 19 },
                new Recipe { RecipeId = 21, ItemId = 21 },
                new Recipe { RecipeId = 22, ItemId = 22 },
                new Recipe { RecipeId = 26, ItemId = 26 },
                new Recipe { RecipeId = 28, ItemId = 28 },
                new Recipe { RecipeId = 30, ItemId = 30 },
                new Recipe { RecipeId = 32, ItemId = 32 },
                new Recipe { RecipeId = 33, ItemId = 33 },
                new Recipe { RecipeId = 34, ItemId = 34 },
                new Recipe { RecipeId = 36, ItemId = 36 },
                new Recipe { RecipeId = 37, ItemId = 37 },
                new Recipe { RecipeId = 42, ItemId = 42 },
                new Recipe { RecipeId = 44, ItemId = 44 },
                new Recipe { RecipeId = 46, ItemId = 46 },
                new Recipe { RecipeId = 52, ItemId = 52 },
                new Recipe { RecipeId = 53, ItemId = 53 },
                new Recipe { RecipeId = 54, ItemId = 54 },
                new Recipe { RecipeId = 64, ItemId = 64 },
                new Recipe { RecipeId = 65, ItemId = 65 },
                new Recipe { RecipeId = 66, ItemId = 66 },
                new Recipe { RecipeId = 67, ItemId = 67 },
                new Recipe { RecipeId = 72, ItemId = 72 },
                new Recipe { RecipeId = 74, ItemId = 74 },
                new Recipe { RecipeId = 80, ItemId = 80 },
                new Recipe { RecipeId = 81, ItemId = 81 },
                new Recipe { RecipeId = 82, ItemId = 82 },
                new Recipe { RecipeId = 83, ItemId = 83 },
                new Recipe { RecipeId = 84, ItemId = 84 },
                new Recipe { RecipeId = 85, ItemId = 85 },
                new Recipe { RecipeId = 86, ItemId = 86 },
                new Recipe { RecipeId = 87, ItemId = 87 },
                new Recipe { RecipeId = 88, ItemId = 88 },
                new Recipe { RecipeId = 89, ItemId = 89 },
                new Recipe { RecipeId = 90, ItemId = 90 },
                new Recipe { RecipeId = 91, ItemId = 91 },
                new Recipe { RecipeId = 92, ItemId = 92 },
                new Recipe { RecipeId = 93, ItemId = 93 },
                new Recipe { RecipeId = 94, ItemId = 94 },
                new Recipe { RecipeId = 95, ItemId = 95 },
                new Recipe { RecipeId = 96, ItemId = 96 },
                new Recipe { RecipeId = 97, ItemId = 97 },
                new Recipe { RecipeId = 98, ItemId = 98 },
                new Recipe { RecipeId = 99, ItemId = 99 },
                new Recipe { RecipeId = 100, ItemId = 100 },
                new Recipe { RecipeId = 101, ItemId = 101 },
                new Recipe { RecipeId = 102, ItemId = 102 },
                new Recipe { RecipeId = 103, ItemId = 103 },
                new Recipe { RecipeId = 104, ItemId = 104 },
                new Recipe { RecipeId = 105, ItemId = 105 },
                new Recipe { RecipeId = 107, ItemId = 107 },
                new Recipe { RecipeId = 108, ItemId = 108 },
                new Recipe { RecipeId = 109, ItemId = 109 },
                new Recipe { RecipeId = 110, ItemId = 110 },
                new Recipe { RecipeId = 111, ItemId = 111 },
                new Recipe { RecipeId = 112, ItemId = 112 },
                new Recipe { RecipeId = 113, ItemId = 113 },
                new Recipe { RecipeId = 114, ItemId = 114 },
                new Recipe { RecipeId = 115, ItemId = 115 },
                new Recipe { RecipeId = 116, ItemId = 116 },
                new Recipe { RecipeId = 118, ItemId = 118 },
                new Recipe { RecipeId = 119, ItemId = 119 },
                new Recipe { RecipeId = 120, ItemId = 120 },
                new Recipe { RecipeId = 121, ItemId = 121 },
                new Recipe { RecipeId = 122, ItemId = 122 },
                new Recipe { RecipeId = 123, ItemId = 123 },
                new Recipe { RecipeId = 124, ItemId = 124 },
                new Recipe { RecipeId = 125, ItemId = 125 },
                new Recipe { RecipeId = 126, ItemId = 126 },
                new Recipe { RecipeId = 127, ItemId = 127 },
                new Recipe { RecipeId = 128, ItemId = 128 },
                new Recipe { RecipeId = 129, ItemId = 129 },
                new Recipe { RecipeId = 130, ItemId = 130 },
                new Recipe { RecipeId = 131, ItemId = 131 },
                new Recipe { RecipeId = 132, ItemId = 132 },
                new Recipe { RecipeId = 133, ItemId = 133 },
                new Recipe { RecipeId = 134, ItemId = 134 },
                new Recipe { RecipeId = 135, ItemId = 135 },
                new Recipe { RecipeId = 136, ItemId = 136 },
                new Recipe { RecipeId = 137, ItemId = 137 },
                new Recipe { RecipeId = 138, ItemId = 138 },
                new Recipe { RecipeId = 139, ItemId = 139 },
                new Recipe { RecipeId = 140, ItemId = 140 },
                new Recipe { RecipeId = 141, ItemId = 141 },
                new Recipe { RecipeId = 142, ItemId = 142 },
                new Recipe { RecipeId = 143, ItemId = 143 },
                new Recipe { RecipeId = 144, ItemId = 144 },
                new Recipe { RecipeId = 146, ItemId = 146 },
                new Recipe { RecipeId = 147, ItemId = 147 },
                new Recipe { RecipeId = 148, ItemId = 148 },
                new Recipe { RecipeId = 149, ItemId = 149 },
                new Recipe { RecipeId = 150, ItemId = 150 },
                new Recipe { RecipeId = 151, ItemId = 151 },
                new Recipe { RecipeId = 152, ItemId = 152 },
                new Recipe { RecipeId = 153, ItemId = 153 },
                new Recipe { RecipeId = 154, ItemId = 154 },
                new Recipe { RecipeId = 155, ItemId = 155 },
                new Recipe { RecipeId = 156, ItemId = 156 },
                new Recipe { RecipeId = 157, ItemId = 157 },
                new Recipe { RecipeId = 158, ItemId = 158 },
                new Recipe { RecipeId = 159, ItemId = 159 },
                new Recipe { RecipeId = 160, ItemId = 160 },
                new Recipe { RecipeId = 161, ItemId = 161 },
                new Recipe { RecipeId = 162, ItemId = 162 },
                new Recipe { RecipeId = 163, ItemId = 163 },
                new Recipe { RecipeId = 164, ItemId = 164 },
                new Recipe { RecipeId = 165, ItemId = 165 },
                new Recipe { RecipeId = 166, ItemId = 166 },
                new Recipe { RecipeId = 167, ItemId = 167 },
                new Recipe { RecipeId = 168, ItemId = 168 },
                new Recipe { RecipeId = 169, ItemId = 169 }
            );
        }
    }
}